management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.159.129:9000/eureka/,http://192.168.159.130:9000/eureka/
    registry-fetch-interval-seconds: 5
    registryFetchIntervalSeconds: 5
    healthcheck:
          enabled: true
  instance:
    hostname: 192.168.159.129
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

secret-key:
  pay-service-key: YZWL!@#$%^&*()_+
  msg-service-key: YZWL!@#$%^&*()_+